<h1><?php echo Mage::helper('testimonials')->__('Give your testimonial about us'); ?></h1>

<form action="<?php echo Mage::getUrl('testimonials/index/send'); ?>" method="post">
    <input type="hidden" value="<?php echo Mage::getSingleton('customer/session')->getCustomerId(); ?>" name="customer_id"/>
    <label for="description">Tell what you think about us</label> <br>
    <textarea cols="100" rows="10" id="description"  class='input-text required-entry' name="description"></textarea>
    <br/><br/>
    <button class="button" type="submit"><span><?php echo Mage::helper('testimonials')->__('Send'); ?></span></button>
</form>
<br/><br/>
<hr/>
<br/>
<?php $testimonials = Mage::getModel('testimonials/testimonial')->getCollection()->addFieldToFilter('enabled', 1); ?>
<h2>What our customers are saying about us </h2>

<ul>
    <?php if($testimonials->getSize() > 0):?>
    <?php foreach($testimonials as $testimonial): ?>
    <li>
        <?php $customer = Mage::getModel('customer/customer')->load($testimonial->getData('customer_id'));?>
        <h4><?php echo $customer->getName(); ?></h4>

        <p>
            <?php echo nl2br($testimonial->getDescription()); ?>
        </p>

    </li>
    <?php endforeach ?>

    <?php else: ?>
        <li><?php echo Mage::helper('testimonials')->__('No  testimonials'); ?></li>
    <?php endif; ?>

</ul>